### ISSUE TITLE
Chekbox before transactions are hard to see

### ISSUE THREAD

**Issue by fefe982** [codinguser/gnucash-android#246]
The UI need to be improved, #196 and #244 are both issues about cannot find a way to delete a transaction.

**Comment by codinguser** [comment]
Long-press to select transactions has now been added from v1.5.2

**Comment by rivaldi8** [comment]
While trying to delete multiple accounts, I've found the UI only allow to select one. By looking at the code I've seen this limitation only applies to accounts (it's possible with transactions). Is there any problem in allowing to select multiple accounts?

**Comment by codinguser** [comment]
This was a decision I made earlier mostly because apart from deleting,
there are really no other actions which (at the moment) can be applied to
multiple accounts.
And since deleting accounts is something we want to be done with caution
anyways, it made sense to limit it to one account selection.
This is even more true when using the new account delete dialog (in develop
branch) to move sub-accounts, or transactions.

**Comment by rivaldi8** [comment]
Ok, thanks for the clarification.
