### ISSUE TITLE
Exporting data since a certain date to QIF is exporting all data instead

### ISSUE THREAD

**Issue by yelneerg** [codinguser/gnucash-android#451]
* Leaving the default export time (time of last export) seems to work.
* Moving the day back by one seems to work.
* However, when I move the date back by two or more days it just exports all data from the beginning as if I had switched the "All time" slider.

*I'm using version 2.0.4 on a galaxy S4 running Android 5.0.1*

**Comment by codinguser** [comment]
Thanks for the detail report. 
@rivaldi8 could you look into it?

**Comment by rivaldi8** [comment]
Sure!

**Comment by rivaldi8** [comment]
I've been doing some testing and verifying the code. All seems to be working correctly. I think you may have had the same misunderstanding I had when I did the first test.

When you specify the date in the export form you are exporting transactions modified (newly added or edited) since that day. This is not the same date as the one specified in the transaction, usually the date you added it.

Are some of your transactions coming from an import? In this case, all these transactions would have as the modified date the date you made the import. As a consequence, an export with a date including the date of the import would include all transactions, independently of de date of each transaction.

**Comment by yelneerg** [comment]
Oh, that would explain it. I imported all my data and then entered in new
entries from before the date I imported the data. It was those entries I
was trying to get out. Is there no way to have it grab data based on the
transaction date instead?

**Comment by codinguser** [comment]
No sorry, there is no way to export entries based on the posted date. 
We need to be able to export transactions again if you change some property after having exported them. This means relying on the date when the transaction was last modified.

We may consider adding some description to the form to explain better what the date actually means.

**Comment by codinguser** [comment]
thanks @rivaldi8

**Comment by rivaldi8** [comment]
@yelneerg, you say you just wanted to export the transactions entered after the import. Note that, independently of the date of these transactions, the modified date still follows the one of the imported transactions. So, if you had done the export leaving the default export date in the form, it should had exported the transactions you expected.

**Comment by yelneerg** [comment]
Hmm, it did not seem to do that. I'll do some testing and double check.
