### ISSUE TITLE
Import GnuCash XML: EACCES (Permission denied)

### ISSUE THREAD

**Issue by Goli4thus** [codinguser/gnucash-android#687]
#### Steps to reproduce the behaviour
1. Export accounts in GnuCash (Ubuntu) (File -> Export -> _Export Accounts_) to _example.gnucash_
2. In App: Settings -> Accounts -> _Import GnuCash XML_
3. Select previously exported _example.gnucash_ file

#### Expected behaviour
Accounts are being imported

#### Actual behaviour
_open failed: EACCES (Permission denied)_ [Imgur](http://i.imgur.com/wlClrVj.jpg)

#### Software specifications
* GnuCash Android version: 2.2.0
* System Android version: 6.0.1 (CyanogenMod 13.1)
* Device type: Xiaomi Mi-4c

#### This might be relevant:
http://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android

**Comment by codinguser** [comment]
GnuCash Android since v2.2.0  does not have permission to read from any location on the SD card. 
I would suggest going through the Navigation Drawer --> Open and then select the file
If your SD card isn't not showing, tap the menu on upper right of the file picker and enable "internal storage".
Let me know if that works for you!

**Comment by Goli4thus** [comment]
Yes that works. Thanks!

BTW: What is the described "Import GnuCash XML" action actually for?

**Comment by codinguser** [comment]
It allows you to pick a place to import from, and actually used to work as you expect it to. 
We only recently removed the permissions for direct access to the SD card. 
So maybe we need to revisit that option and adapt it to the new procedures.

**Comment by Goli4thus** [comment]
Alright, thanks for the explanation!

**Comment by DeLaRiva** [comment]
Hi,
I've the same or a similar problem on the android version. I faces the same error when I try to import a gnucash file from my dropbox where I saved the file I've created in Ubuntu.
Circumventing is not possible since "opening" is only available for google drive (but in "importint" dropbox is there).
