### ISSUE TITLE
Application no longer opens successfully and crashes when opening.

### ISSUE THREAD

**Issue by targzip** [codinguser/gnucash-android#749]
#### Steps to reproduce the behaviour
1. I have Gnucash 1.5.5 installed on a Sony Xperia Z2 with Android 5.0.2. 
2. When I try to open, the application no longer opens successfully. I get white screen for a second or so and then "Unfortunately, GnuCash has stopped."
3. This is 100% reproducible ever since it started happening.
4. This did not start immediately after the update to 1.5.5, only after a couple of days.

#### Expected behaviour

The app should open and run normally.

#### Actual behaviour

The app crashes at opening.

#### Software specifications
* GnuCash Android version: 1.5.5
* System Android version: 5.0.2
* Device type: Sony Xperia Z2

**Comment by targzip** [comment]
I have updated the phone to Android 6.0.1 but the issue remains:  "Unfortunately, GnuCash has stopped."

**Comment by MisterY** [comment]
Any particular reason not to use the [latest](https://github.com/codinguser/gnucash-android/releases/latest) release?

**Comment by targzip** [comment]
I wasn't able to install it the last time I tried.

**Comment by targzip** [comment]
Retried the installation of 2.2.1 and it worked. However, the problem persists. "Unfortunately, GnuCash has stopped."

**Comment by MisterY** [comment]
Interesting. In any case, if you are on the net then I'm sure they are getting the crash reports.

**Comment by targzip** [comment]
Is there any way to backup my Gnucash data when I am not able to open the app? 

(yes, I am on the net and I suppose they are getting the crash reports)

**Comment by rivaldi8** [comment]
Sorry, unless your phone is rooted it's not possible, as far as I know. 

The only temporary solution I can think of, is to offer you a [devel APK](https://my.owndrive.com/index.php/s/3aqHJeHYavJg1Cf). It will be installed as a separate GnuCash application which you can use while we try to fix the issue. Then, when you update to the version with the fix, you'll be able to access your data again.

This is only really worth if you use it to enter transactions on the go and import them later on the desktop. Otherwise you would have to manually re-enter the transactions from the devel version into the production one.

I haven't found your crash report yet. Sometimes it takes a while. Or maybe I've just overlooked it. I'll continue looking and working on fixing possible start-up crashes.

**Comment by rivaldi8** [comment]
I forgot we make automatic backups on version updates. Look into `Android/data/org.gnucash.android/files/` of your internal storage.

**Comment by rivaldi8** [comment]
I haven't found any crash report referencing your device, but some of them might be related to multiple books.

Are you using multiple books? If that's the case, how did you add them (opening/importing a .gnca file, creating it from "manage books"...)?

**Comment by rivaldi8** [comment]
Please, could you verify if version 2.3.0 has solved the problem?

**Comment by targzip** [comment]
Hi,

Sorry for not having replied previously.

No, version 2.3.0 did not solve the problem. I tried the updates as they were appearing but nothing solved the issue. I ended up uninstalling it on the Xperia phone last weekend :(

I will reinstall it later and restart using it from scartch and this time I will keep my data backed up elsewhere too. If some other issue should arise then, I'll report it.

Thanks
